import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Component/Navbar'
import { ToastContainer } from 'react-toastify'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Stay_BOOK_APP',
  description: 'Generated by Akash Sabe',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToastContainer />
        <Navbar/>
        {children}
        
        </body>
    </html>
  )
}
